### ISSUE TITLE
ti_monocle_ddrtree with reduction_method = "DDRTree" fails to execute

### ISSUE THREAD

**Issue by pablommesas** [dynverse/ti_monocle_ddrtree#2]
I have noticed that when executing the **ti_monocle_ddrtree** in default mode, the program is not using the default value defined in the definition.yml for the **reduction_method** parameter:
```
parameters:
  - id: reduction_method
    type: character
    default: DDRTree
    values: DDRTree
    description: A character string specifying the algorithm to use for dimensionality
      reduction.
```
The program executes successfully but instead of using reduction_method = "DDRTree" it is using the **reduction_method = "ICA"**. 

>     trajectory <- infer_trajectory(dataset, "monocle_ddrtree", verbose = TRUE)

```
Executing 'monocle_ddrtree' on 'real/gold/myoblast-differentiation_trapnell'
With parameters: list(reduction_method = "ICA", max_components = 2L, norm_method = "log",     auto_param_selection = TRUE, filter_features = TRUE, filter_features_mean_expression = 0.1),
inputs: counts, and
priors : 
```
When trying to execute the method by forcing the parameter: **reduction_method = "DDRTree"**. 
>    parameters <- list(reduction_method = "DDRTree", max_components = 2L, norm_method = "none", auto_param_selection = TRUE, filter_features = TRUE, filter_features_mean_expression = 0.1)

>    trajectory <- infer_trajectory(dataset, "monocle_ddrtree", parameters = parameters, verbose = TRUE)

```
Executing 'monocle_ddrtree' on 'real/gold/myoblast-differentiation_trapnell'
With parameters: list(reduction_method = "DDRTree", max_components = 2L, norm_method = "none",     auto_param_selection = TRUE, filter_features = TRUE, filter_features_mean_expression = 0.1),
inputs: counts, and
priors :
```
The program uses the desired reduction_method but fails to successfully to finish returning the following error:
```
Error in igraph::as_data_frame(gr, "edges") : Not a graph object
Calls: %>% -> eval -> eval -> <Anonymous>
Execution halted
Error: Error during trajectory inference
```
I believe the error is related to the fact that "ICA" and "DDRTree" reduction methods store the trajectory representation differently.

**Comment by rcannood** [comment]
This problem was fixed in da408f0, but it seems your area still running an older version of dynmethods and ti_monocle_ddrtree. Please update dynmethods : `devtools::install_github("dynverse / dynmethods")`.

Let me know whether this solves your problem.

**Comment by pablommesas** [comment]
Perfect! This solved the problem. Thanks.

**Comment by rcannood** [comment]
:+1:
